apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: esa-test
spec:
  ## The name of the Elasticsearch cluster to be scaled automatically.
  elasticsearchRef:
    name: "mtesc"
  ## The autoscaling policies.
  policies:
    - name: masters
      roles: ["master", "data", "ingest", "transform"]
      resources:
        nodeCount:
          min: 1
          max: 2
        cpu:
          min: 1
          max: 2
        memory:
          min: 2Gi
          max: 2Gi
        storage:
          min: 20Gi
          max: 20Gi