apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mastengsc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true