{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.vpaScaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
  namespace: elastic-system
  labels:
    app: {{ .Release.Name }}-lbl
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: 'elasticsearch'
      minAllowed:
        cpu: 500m
        memory: 2Gi
  targetRef:
    apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-lab-es-masters
  updatePolicy:
    {{- $mode := "Off" | quote -}}
    {{ if .Values.elasticsearch.vpaScaling.mode }}
    {{- $mode = .Values.elasticsearch.vpaScaling.mode | quote -}}
    {{ end}}
    updateMode: {{ $mode }}
{{- end }}